
#ifdef _WIN32
#include <windows.h>
#endif

#include <math.h>
#include <stdlib.h>
#include <inttypes.h>
#include <time.h>
#include <stdio.h>
#include <stdint.h>
/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.15 (master) -  8 Jan 2020 10:53
*/

/*
   gradient     of useful results: u *ub *Ib I function_0b
   with respect to varying inputs: u *ub *Ib I function_0b
   RW status of diff variables: u:incr *ub:in-out *Ib:in-out I:incr
                function_0b:incr
   Plus diff mem management of: ub:in Ib:in

        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.15 (master) -  8 Jan 2020 10:53


  Differentiation of function_0 in reverse (adjoint) mode:
   gradient     of useful results: u function_0 I
   with respect to varying inputs: u I
   RW status of diff variables: u:incr function_0:in-killed I:incr
*/
void function_0_b_b(double u, double *ub0, double *ub, double *ubb, double I, 
        double *Ib0, double *Ib, double *Ibb, double function_0b, double *
        function_0bb) {
    double p = 4*4*(u*(1-u)*(I*(1-I)));
    double pb = 0.0;
    double pbb = 0.0;
    double tempb;
    double tempbb;
    double tempb0;
    double tempb0b;
    double tempb1;
    double tempb1b;
    double function_0;
    pb = function_0b;
    tempb = 4*4*pb;
    tempb0 = (1-u)*(1-I)*tempb;
    tempb1 = u*I*tempb;
    tempb1b = -((1-u)*(*Ibb)) - (1-I)*(*ubb);
    tempb0b = u*(*Ibb) + I*(*ubb);
    *ub0 = *ub0 + (tempb0+tempb1)*(*Ibb) + I*tempb*tempb1b - tempb*(1-I)*
        tempb0b;
    *Ib0 = *Ib0 + (tempb0+tempb1)*(*ubb) + u*tempb*tempb1b - (1-u)*tempb*
        tempb0b;
    tempbb = u*I*tempb1b + (1-u)*(1-I)*tempb0b;
    pbb = 4*4*tempbb;
    *function_0bb = *function_0bb + pbb;
}

void read_file_to_array(char *filename, double *args, int num_params, int num_vars)
{
    FILE *file = fopen(filename, "r");

    if (file != NULL)
    {

        char line[200];
        int i = 0;

        for (int i = 0; i < num_params * num_vars; i++)
        {
            fscanf(file, "%lf", &args[i]);
        }

        fclose(file);
    }
    else
    {
        perror(filename); /* why didn't the file open? */
    }
}

/*
    Expects command line arguments: num_params num_vars params_filename output_filename
*/
int main(int argc, char *argv[])
{

    printf("I am running...");

    // read command line arguments
    char *ptr;

    int num_params = (int)strtol(argv[1], &ptr, 10);
    int num_vars = (int)strtol(argv[2], &ptr, 10);
    int num_ders = (num_vars * num_vars);
    char *params_filename = argv[3];
    char *output_filename = argv[4];

    double *values = malloc(num_params * num_vars * sizeof(double));
    double *ders = malloc(num_params * num_ders * sizeof(double));

    read_file_to_array(params_filename, values, num_params, num_vars);

#ifdef _WIN32

    LARGE_INTEGER StartingTime, EndingTime, ElapsedMicroseconds;
    LARGE_INTEGER Frequency;

    QueryPerformanceFrequency(&Frequency);
    QueryPerformanceCounter(&StartingTime);

    // Activity to be timed
    compute(values, num_params, ders);

    QueryPerformanceCounter(&EndingTime);
    ElapsedMicroseconds.QuadPart = EndingTime.QuadPart - StartingTime.QuadPart;

    // ElapsedMicroseconds.QuadPart *= 1000000;
    // ElapsedMicroseconds.QuadPart /= Frequency.QuadPart;

    double delta = (ElapsedMicroseconds.QuadPart) / (double)Frequency.QuadPart; // seconds

#else

//double u, double *ub0, double *ub, double *ubb, double I, 
        // double *Ib0, double *Ib, double *Ibb, double function_0b, double *
        // function_0bb
    struct timespec tstart = {0, 0}, tend = {0, 0};
    clock_gettime(CLOCK_MONOTONIC, &tstart);
    for (int i = 0; i < num_params; i++) {
		double u = values[i * 2 + 0];
		double ub0 = 0;
        double ub = 0;
        double ubb = 1;
		double I = values[i * 2 + 1];
		double Ib0 = 0;
        double Ib = 0;
        double Ibb = 1;
		double function_0b = 1;
        double function_0bb = 0;
		function_0_b_b(u, &ub0, &ub, &ubb, I, &Ib0, &Ib, &Ibb, function_0b, &function_0bb);
		
        printf("u=%f, ub0=%f, ub=%f, ubb=%f, I=%f, Ib0=%f, Ib=%f, Ibb=%f\n", u, ub0, ub, ubb, I, Ib0, Ib, Ibb);
        
        // ders[i * 4 + 0] = ub;
		// ders[i * 4 + 1] = mb;
    }
    clock_gettime(CLOCK_MONOTONIC, &tend);
    double delta = ((double)tend.tv_sec + 1.0e-9 * tend.tv_nsec) - ((double)tstart.tv_sec + 1.0e-9 * tstart.tv_nsec); // seconds
#endif

    FILE *fp;

    fp = fopen(output_filename, "w+");
    printf("%f ", delta);
    fprintf(fp, "%f ", delta);

    for (int i = 0; i < num_params * num_ders; i++)
    {
        fprintf(fp, "%f ", ders[i]);
        printf("%f", ders[i]);
    }
    fclose(fp);
    return 0;
}
