/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.15 (master) -  8 Jan 2020 10:53
*/


/*
  Differentiation of function_0 in reverse (adjoint) mode:
   gradient     of useful results: function_0 T
   with respect to varying inputs: T
   RW status of diff variables: function_0:in-killed T:incr
*/
void function_0_b(double T, double *Tb, double function_0b) {
    double p = 4*(T*(1-T));
    double pb = 0.0;
    double function_0;
    pb = function_0b;
    *Tb = *Tb + (4-8*T)*pb;
}
