/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.15 (develop) -  7 Jan 2020 16:27
*/
// #include <adBuffer.h>

/*
  Differentiation of function_0 in reverse (adjoint) mode:
   gradient     of useful results: d e f g h j k l m n o q r s
                t u v w x y z function_0 a b c
   with respect to varying inputs: d e f g h j k l m n o q r s
                t u v w x y z a b c
   RW status of diff variables: d:incr e:incr f:incr g:incr h:incr
                j:incr k:incr l:incr m:incr n:incr o:incr q:incr
                r:incr s:incr t:incr u:incr v:incr w:incr x:incr
                y:incr z:incr function_0:in-killed a:incr b:incr
                c:incr
*/
void function_0_b(double a, double *ab, double b, double *bb, double c, double
        *cb, double d, double *db, double e, double *eb, double f, double *fb,
        double g, double *gb, double h, double *hb, double j, double *jb, 
        double k, double *kb, double l, double *lb, double m, double *mb, 
        double n, double *nb, double o, double *ob, double q, double *qb, 
        double r, double *rb, double s, double *sb, double t, double *tb, 
        double u, double *ub, double v, double *vb, double w, double *wb, 
        double x, double *xb, double y, double *yb, double z, double *zb, 
        double function_0b) {
    double p = 0;
    double pb = 0.0;
    double temp;
    double temp0;
    double temp1;
    double temp2;
    double temp3;
    double temp4;
    double temp5;
    double temp6;
    double temp7;
    double temp8;
    double temp9;
    double temp10;
    double temp11;
    double temp12;
    double temp13;
    double temp14;
    double tempb;
    double tempb0;
    double tempb1;
    double tempb2;
    double tempb3;
    double tempb4;
    double tempb5;
    double tempb6;
    double tempb7;
    double tempb8;
    double tempb9;
    double tempb10;
    double tempb11;
    double tempb12;
    double tempb13;
    double tempb14;
    double function_0;
    pb = function_0b;
    temp = w*x;
    temp0 = u*v*temp;
    temp1 = s*t;
    temp2 = q*r*temp1;
    temp3 = temp2*temp0;
    temp4 = n*o;
    temp5 = l*m*temp4;
    temp6 = j*k;
    temp7 = g*h*temp6;
    temp8 = e*f;
    temp9 = b*c*temp8;
    temp10 = temp9*y*z;
    temp11 = temp10*temp7*temp5;
    temp12 = a*d - temp11*temp3;
    temp13 = a*d - b*c;
    temp14 = temp13*temp12;
    tempb = (1.0/temp14+1)*pb;
    tempb0 = -((a*a+b*b+c*c+d*d)*pb/(temp14*temp14));
    tempb1 = temp12*tempb0;
    tempb2 = temp13*tempb0;
    *ab = *ab + d*tempb2 + d*tempb1 + 2*a*tempb;
    *db = *db + a*tempb2 + a*tempb1 + 2*d*tempb;
    tempb3 = -(temp7*temp5*temp3*tempb2);
    tempb6 = -(temp10*temp3*tempb2);
    tempb11 = -(temp0*temp11*tempb2);
    tempb13 = -(temp2*temp11*tempb2);
    *ub = *ub + v*temp*tempb13;
    *vb = *vb + u*temp*tempb13;
    tempb14 = u*v*tempb13;
    *wb = *wb + x*tempb14;
    *xb = *xb + w*tempb14;
    *qb = *qb + r*temp1*tempb11;
    *rb = *rb + q*temp1*tempb11;
    tempb12 = q*r*tempb11;
    *sb = *sb + t*tempb12;
    *tb = *tb + s*tempb12;
    tempb7 = temp5*tempb6;
    tempb9 = temp7*tempb6;
    *lb = *lb + m*temp4*tempb9;
    *mb = *mb + l*temp4*tempb9;
    tempb10 = l*m*tempb9;
    *nb = *nb + o*tempb10;
    *ob = *ob + n*tempb10;
    *gb = *gb + h*temp6*tempb7;
    *hb = *hb + g*temp6*tempb7;
    tempb8 = g*h*tempb7;
    *jb = *jb + k*tempb8;
    *kb = *kb + j*tempb8;
    tempb4 = y*z*tempb3;
    *yb = *yb + z*temp9*tempb3;
    *zb = *zb + y*temp9*tempb3;
    *bb = *bb + c*temp8*tempb4 + 2*b*tempb - c*tempb1;
    *cb = *cb + b*temp8*tempb4 + 2*c*tempb - b*tempb1;
    tempb5 = b*c*tempb4;
    *eb = *eb + f*tempb5;
    *fb = *fb + e*tempb5;
}
